FROM bitnami/nginx


# Deliver the dist folder with Nginx
ARG CLIENT_BUILD_TARGET
ARG PUBLIC_PATH
COPY conf-candidat-dso /etc/nginx/conf.d/default.conf
COPY conf-candidat-dso /opt/bitnami/nginx/conf/server_blocks/conf-candidat.conf
COPY dist-candidat /opt/bitnami/nginx/html/candidat
