
export default {
  app_name: 'Candilib',
  // INFO: message for ScheduleInspector
  delete_whole_day_s_places: 'Supprimer la journée',
  delete_morning_places: 'Supprimer la matinée',
  delete_afternoon_places: `Supprimer l'après-midi`,
  recevoir_les_bordereaux_inspecteurs: 'Recevoir les bordereaux des inspecteurs du',
  les_bordereaux_inspecteurs: 'Les bordereaux inspecteurs',
  les_bordereaux_inspecteurs_seront_envoyes_a_l_adresse: `Les bordereaux inspecteurs seront envoyés à l'adresse courriel`,
  annuler: 'Annuler',
  envoyer: 'Envoyer',
  nom: 'Nom',
  neph: 'Neph',
  mobile: 'Portable',
  loading: 'Chargement en cours',
  gestion_des_plannings: 'Gestion des plannings',
  tableau_de_bord: 'Tableau de bord',
  total_places: 'Total places',
  affecter_le_candidat: 'Affecter le candidat',
  sur_la_place_du: 'sur la place du',
  au_centre: 'au centre',
  send_bordereaux: 'Envoyer les bordereaux aux inspecteurs du',
  send_bordereaux_for_ipcsr_email: `Les bordereaux seront envoyés aux adresses courriels de chaque inspecteurs,
    si l'un des courriels n'arrive pas à déstination, un courriel vous sera envoyé afin de vous prevenir.`,
  receive_bordereaux_for_ipcsr_email: 'Recevoir les bordereaux des inspecteurs du',
  send_bordereaux_to_email: `Les bordereaux inspecteurs seront envoyés à l'adresse courriel:`,
  non_renseignee: `Non renseignée`,
}
