
export default {
  app_name: 'Candilib',
  // INFO: message for ScheduleInspector
  delete_whole_day_s_places: 'Supprimer la journée',
  delete_morning_places: 'Supprimer la matinée',
  delete_afternoon_places: `Supprimer l'après-midi`,
  recevoir_les_bordereaux_inspecteurs: 'Recevoir les bordereaux des inspecteurs du',
  les_bordereaux_inspecteurs: 'Les bordereaux inspecteurs',
  les_bordereaux_inspecteurs_seront_envoyes_a_l_adresse: `Les bordereaux inspecteurs seront envoyés à l'adresse courriel`,
  annuler: 'Annuler',
  envoyer: 'Envoyer',
  nom: 'Nom',
  neph: 'Neph',
  mobile: 'Portable',
  loading: 'Chargement en cours',
  gestion_des_plannings: 'Gestion des plannings',
  tableau_de_bord: 'Tableau de bord',
  total_places: 'Total places',
  affecter_le_candidat: 'Affecter le candidat',
  sur_la_place_du: 'sur la place du',
  au_centre: 'au centre',
  send_bordereaux: 'Envoyer les bordereaux aux inspecteurs du',
  send_bordereaux_for_ipcsr_email: `Les bordereaux seront envoyés aux adresses courriels de chaque inspecteurs,
    si l'un des courriels n'arrive pas à déstination, un courriel vous sera envoyé afin de vous prevenir.`,
  receive_bordereaux_for_ipcsr_email: 'Recevoir les bordereaux des inspecteurs du',
  send_bordereaux_to_email: `Les bordereaux inspecteurs seront envoyés à l'adresse courriel : `, // eslint-disable-line no-irregular-whitespace
  date_first_day_of_week: `Date du premier jour de la semaine N°`,
  total_of_week: `Total de la Semaine`,
  non_renseignee: `Non renseignée`,
  booked_places_100_pourcent: '100% des places sont réservées',
  booked_places_more_than_50_pourcent: '50% ou plus des places sont reservées',
  booked_places_lower_than_50_pourcent: 'Moins de 50% des places sont reservées',
  export_stats_csv: `Export Stats CSV`,
  export_places_stats_csv: `Export places Stats CSV`,
  departement: `Département : `, // eslint-disable-line no-irregular-whitespace
  resultats_a_lexamen: `Résultats à l'examen`,
  de_reussite: `de réussite`,
  egale_recus_divise_reçus_plus_echecs: `= reçus / (reçus + échecs)`,
  d_absenteisme: `d'absentéisme`,
  egale_absents_divise_examens_passes: `= absents / examens passés`,
  de_non_examines: `de non-examinés`,
  egale_non_examinés_divise_examens_passes: `= non examinés / examens passés`,
  examens_passes: `Examens Passés`,
  places_examens: `Places d'examens`,
  de_remplissage_de_places_passees: `de remplissage de places passées`,
  egale_examens_passes_divise_places_proposees_dans_le_passe: `= examens passés / places proposées dans le passé`,
  de_remplissage_de_places_a_venir: `de remplissage de places à venir`,
  egale_reservation_a_venir_divise_places_proposees_dans_le_futur: `= reservation à venir / places proposées dans le futur`,
}
