
export default {
  app_name: 'Candilib',
  app_subtitle: 'Réservez votre place d\'examen',
  preinscription_title: 'Candilib',
  preinscription_form_notice: 'Tous les champs marqués d\'un astérisque * sont obligatoires',
  preinscription_neph: 'NEPH (obligatoire)',
  preinscription_neph_erreur: 'Le code neph n\'est pas valide',
  preinscription_nom_naissance: 'Nom de naissance (obligatoire)',
  preinscription_prenom: 'Prénom',
  preinscription_email: 'Courriel (obligatoire)',
  preinscription_email_erreur: 'L\'adresse courriel doit être valide',
  preinscription_email_vide: 'Veuillez renseigner votre adresse courriel',
  preinscription_mobile: 'Portable (obligatoire)',
  preinscription_mobile_erreur: 'Le numéro de téléphone doit être valide',
  preinscription_adresse: 'Adresse (obligatoire)',
  preinscription_bouton_submit: 'Pré-inscription',
  preinscription_bouton_deja_inscrit: 'Déjà Inscrit ?',
  preinscription_bouton_mentions_legales: 'Mentions légales',
  preinscription_bouton_faq: 'Une question ?',
  preinscription_magic_link_title: 'Recevez un lien de connexion',
  preinscription_magic_link_msg: 'Envoyez un Lien de connexion',
  preinscription_bouton_magic_link: 'Envoyez un Lien de connexion',
  preinscription_formulaire_invalide: 'Veuillez remplir le formulaire',
  preinscription_magic_link_invalide: 'Veuillez fournir votre adresse courriel',
  preinscription_magic_link_envoyé: 'Un lien de connexion vous a été envoyé. Veuillez consulter votre boîte courriel',
  home_choix_du_centre: 'Choix du centre',
  confirmation_reservation_title: 'Confirmation',
  confirmation_reservation_subtitle: 'Vous avez choisi de passer l’épreuve pratique du permis à',
  confirmation_reservation_word: 'Le',
  confirmation_reservation_checkbox_title: 'Avez-vous pensez à vérifier :',
  confirmation_reservation_checkbox_accompagner: 'qu’une personne peut vous accompagner *',
  confirmation_reservation_checkbox_double_commande: 'qu’une voiture à double commande est disponible *',
  confirmation_reservation_boutton_retour: 'Retour',
  confirmation_reservation_boutton_confirmation: 'Confirmer',
  recap_reservation_confirmee: 'Votre réservation est confirmée',
  recap_reservation_email_confirmee: 'Un email de confirmation vous a été envoyé à l\'adresse',
  recap_reservation_boutton_annuler: 'Annuler',
  recap_reservation_modal_annuler_body: 'Texte à définir recap_reservation_modal_annuler_body',
  recap_reservation_modal_annuler_boutton_retour: 'Retour',
  recap_reservation_modal_annuler_boutton_confirmer: 'Confirmer',
  recap_reservation_boutton_modifier: 'Modifier',
  recap_reservation_boutton_renvoyer_email: 'Renvoyer',
}
