
export default {
  app_name: 'Candilib',
  app_subtitle: 'Réservez votre place d\'examen',
  preinscription_title: 'Candilib',
  preinscription_form_notice: 'Tous les champs marqués d\'un astérisque * sont obligatoires',
  preinscription_neph: 'NEPH (obligatoire)',
  preinscription_neph_erreur: 'Le code neph n\'est pas valide',
  preinscription_nom_naissance: 'Nom de naissance (obligatoire)',
  preinscription_prenom: 'Prénom',
  preinscription_email: 'Courriel (obligatoire)',
  preinscription_email_erreur: 'L\'adresse courriel doit être valide',
  preinscription_email_vide: 'Veuillez renseigner votre adresse courriel',
  preinscription_mobile: 'Portable (obligatoire)',
  preinscription_mobile_erreur: 'Le numéro de téléphone doit être valide',
  preinscription_adresse: 'Adresse (obligatoire)',
  preinscription_bouton_submit: 'Pré-inscription',
  preinscription_bouton_deja_inscrit: 'Déjà Inscrit ?',
  preinscription_bouton_mentions_legales: 'Mentions légales',
  preinscription_bouton_faq: 'Une question ?',
  preinscription_magic_link_title: 'Recevez un lien de connexion',
  preinscription_magic_link_msg: 'Envoyez un Lien de connexion',
  preinscription_bouton_magic_link: 'Envoyez un Lien de connexion',
  preinscription_formulaire_invalide: 'Veuillez remplir le formulaire',
  preinscription_magic_link_invalide: 'Veuillez fournir votre adresse courriel',
  preinscription_magic_link_envoyé: 'Un lien de connexion vous a été envoyé. Veuillez consulter votre boîte courriel',
  candidat_home_choix_du_centre: 'Choix du centre',
  candidat_confirmation_reservation_title: 'Confirmation',
  candidat_confirmation_reservation_subtitle: 'Vous avez choisi de passer l’épreuve pratique du permis à',
  candidat_confirmation_reservation_word: 'Le',
  candidat_confirmation_reservation_checkbox_title: 'Avez-vous pensez à vérifier :',
  candidat_confirmation_reservation_checkbox_accompagner: 'qu’une personne peut vous accompagner *',
  candidat_confirmation_reservation_checkbox_double_commande: 'qu’une voiture à double commande est disponible *',
  candidat_confirmation_reservation_boutton_retour: 'Retour',
  candidat_confirmation_reservation_boutton_confirmation: 'Confirmer',
  candidat_recap_reservation_confirmée: 'Votre réservation est confirmée',
  candidat_recap_reservation_email_confirmée: 'Un email de confirmation vous a été envoyé à l\'adresse',
  candidat_recap_reservation_boutton_annuler: 'Annuler',
  candidat_recap_reservation_modal_annuler_text_body: 'Veniam consectetur consequat sint dolore ad amet velit cupidatat nulla reprehenderit proident exercitation. Labore excepteur laborum officia nostrud cupidatat ullamco. Quis eiusmod do ut fugiat veniam dolore velit elit irure tempor nostrud. Cillum deserunt ut labore amet magna incididunt enim occaecat deserunt anim laboris occaecat.',
  candidat_recap_reservation_modal_annuler_boutton_retour: 'Retour',
  candidat_recap_reservation_modal_annuler_boutton_confirmer: 'Confirmer',
  candidat_recap_reservation_boutton_modifier: 'Modifier',
  candidat_recap_reservation_boutton_renvoyer_email: 'Renvoyer',
}
