@remote-server = http://localhost:9000/api/automate 

###
{{remote-server}}/version

###
{{remote-server}}/scheduler/status

###
POST {{remote-server}}/scheduler/stop

###
POST {{remote-server}}/scheduler/start

###
{{remote-server}}/jobs
###
{{remote-server}}/jobs/HELLO
