FROM keymetrics/pm2:10-alpine

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
EXPOSE 8000

# Bundle APP files
COPY src src/
COPY babel.config.js package.json package-lock.json ./
COPY ecosystem.config.js .

# Install app dependencies
ENV NPM_CONFIG_LOGLEVEL warn
RUN npm install
RUN npm run build

# Expose the listening port of your app
EXPOSE 8000

CMD [ "pm2-runtime", "start", "ecosystem.config.js" ]
