#######################
# Step 1: Base target #
#######################
FROM node:14.15.0-slim

# Base dir /app
WORKDIR /app

COPY dist dist/

COPY dev-setup dev-setup/

COPY boot-dev.js .

COPY db db/

COPY babel.config.js .

COPY .env ..env

COPY src src/

COPY package.json .

COPY package-lock.json .

COPY ecosystem.config.js .


# Install production dependencie
RUN npm install 

#RUN DB MIGRATION
CMD [ "npm", "run", "dev-setup"]