export * from './body-mail-template'
export * from './cancel-booking-template'
export * from './convocation-template'
export * from './epreuve-etg-ko-template'
export * from './epreuve-pratique-ok-template'
export * from './epreuve-pratique-ok-before-template'
export * from './inscription-ko-template'
export * from './inscription-ok-template'
export * from './inscription-valid-template'
export * from './validation-email-template'
export * from './cancel-booking-by-admin-template'

export * from './mail.constants'
